### ISSUE TITLE
No communication between IDP and LDAP

### ISSUE THREAD

**Issue by damas** [AAROC/DevOps#122]
Dear Marco,
We shifted our IDP and LDAP servers to be on the firewall and so they have internal private network with 192.168.148.34 (IDP) and 41.93.32.33 (LDAP) however they are both NATed to the public 41.93.32.34 (IDP) and 41.93.32.33 (LDAP). 
I have the problem after connecting to the firewall but before everything was OK, it seems that the IDP and LDAP can't communicate as I cant login to the IDP with error Invalid username or password is wrong.
How to configure LDAP and IDP to have internal communication over this private network?

Rgds,
Damas

**Comment by brucellino** [comment]
Update on this ticket ; at this site, all names are resolved to their external IPs. The communication between IDP and LDAP should be happening on the private network, however there is no communication between them. 

The LDAP does not respond on ports 389 or 636 either on the public or private network (ldapsearches can't connect error -1)

On the LDAP server, however the server is listening: 
```
netstat -tan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address               Foreign Address             State      
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN      
tcp        0      0 0.0.0.0:636                 0.0.0.0:*                   LISTEN      
tcp        0      0 0.0.0.0:389                 0.0.0.0:*                   LISTEN      
tcp        0     96 192.168.148.33:22           193.206.208.201:45042       ESTABLISHED 
tcp        0      0 :::22                       :::*                        LISTEN      
tcp        0      0 ::1:25                      :::*                        LISTEN      
tcp        0      0 :::636                      :::*                        LISTEN      
tcp        0      0 :::389                      :::*                        LISTEN      
```

When running ldapsearches directly on the ldap server, we do indeed get the tree. So, something is preventing the ldap server from talking to the outside world.

**Comment by brucellino** [comment]
By disabling the firewall, I checked that ldap connections worked. I've used the internal LDAP server address for the TERNET site, since there is this host name resolution problem. Added a line in sysconfig that allowed connections from the sgw to the ldap server : 

```
-A INPUT -s 192.168.148.43 -p tcp -m state --state NEW -m tcp --dport 636 -j ACCEPT
-A INPUT -s 192.168.148.43 -p tcp -m state --state NEW -m tcp --dport 389 -j ACCEPT
```
Something similar should be done for the idp.

**Comment by brucellino** [comment]
@damas  can you comment on whether this was resolved or not ?

**Comment by brucellino** [comment]
@damas we are preparing to make the pre-release v0.0.4 and I'm going through the issues opened inn this milestone. Can you comment on whether we can close this or not ?

**Comment by damas** [comment]
Hi Bruce,
Sorry for being silence for awhile, was at field running some workshops/trainings and was not be able to respond on this.
I don’t know if the problem with my IDP relate with LDAP any more but what I am getting problem with IDP are;
I can’t login with error, "wrong username or incorrect password”
Just to solve error #1 above, tried to reset password by going "forget your password” link and entered my email address (for this case, the default/primary email is required, the email used during registration) but the error I am getting is related to mail problem as i gives an error of HTTP Status 500 - Type Exception report, description: The server encountered and internal error () that prevented it from fulfilling this request. 
So, with this scenario I don’t know if the problem with IDP to communicate with LDAP is persists as well. I would therefore request assistant please.
Rgds,
Damas

**Comment by brucellino** [comment]
Thanks Damas, I'll keep this open then and we'll see about fixing it soon.

**Comment by brucellino** [comment]
This might have been fixed by #199

**Comment by brucellino** [comment]
I have just checked this this morning, seems fine.

**Comment by brucellino** [comment]
# Solution 

_probably_ a firewall change.
