### ISSUE TITLE
Installing sagrid.ac.za: incorrect VOMS DN

### ISSUE THREAD

**Issue by shaze** [AAROC/DevOps#15]
Any clues where to look? 

 INFO: Executing function: config_glite_ui 
   INFO: Executing function: config_vomses 
   ERROR: VOMSES parameter for VO 'sagrid.ac.za' has incorrect DN or alias
   ERROR: Error during the execution of function: config_vomses
   ERROR: Error during the configuration.Exiting.                              [FAILED]
   ERROR: One of the functions returned with error without specifying its nature !

**Comment by brucellino** [comment]
just an update - got this issue again today. Removing the "on-hold" tag

**Comment by brucellino** [comment]
fixed by 927374f
