### ISSUE TITLE
Attributes missing error when SAML login is attempted

### ISSUE THREAD

**Issue by brucellino** [AAROC/DevOps#162]
On the DIT Science Gateway, we are getting the http://sgw.ternet.or.tz/attributes_missed error. This is due to some missing Shibboleth configuration.

**Comment by damas** [comment]
Hi team,
How to fix that, is there anything I can do over here?
Rgds,
Damas

**Comment by brucellino** [comment]
Nope, there's not much you can do - on the next set of commits, you should be able to do a full deploy. We will also be able to finish the [wiki page](wiki/liferay-csgf-playbook)

**Comment by brucellino** [comment]
Error in the shibboleth logs shows that the federation metadata is missing : 

```
2015-01-21 14:25:52 ERROR XMLTooling.libcurl.InputStream : error while fetching https://gridp.garr.it/metadata/gridp.xml: (59) Unknown cipher in list: ALL:!aNULL:!LOW:!EXPORT:!SSLv2
2015-01-21 14:25:52 ERROR XMLTooling.libcurl.InputStream : on Red Hat 6+, make sure libcurl used is built with OpenSSL
```

This seems to be a problem with the downloading of the metadata.

**Comment by brucellino** [comment]
Installing libcurl-openssl seems to fix this

**Comment by brucellino** [comment]
We have the same problem on the sagrid science gateway
