### ISSUE TITLE
environment must be a dictionary, received java_env

### ISSUE THREAD

**Issue by okoliec** [AAROC/DevOps#171]
Please am getting this new error during my idp install

TASK: [shibboleth-idp | Create the installation directory] ******************** 
ok: [idp.ugb.sn] => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "owner": "ansible", "path": "/root/idp", "size": 1024, "state": "directory", "uid": 1001}

TASK: [shibboleth-idp | Unpack the tarball] *********************************** 
skipping: [idp.ugb.sn]
ok: [idp.ugb.sn] => {"changed": false, "msg": "skipped, since /root/idp/shibboleth-identityprovider-2.4.1/install.sh exists", "skipped": true}

TASK: [shibboleth-idp | Copy the installer] *********************************** 
ok: [idp.ugb.sn] => {"changed": false, "gid": 0, "group": "root", "mode": "0744", "owner": "root", "path": "/root/idp/shibboleth-identityprovider-2.4.1/install-shib.expect", "size": 419, "state": "file", "uid": 0}

TASK: [shibboleth-idp | Install the package] ********************************** 
fatal: [idp.ugb.sn] => environment must be a dictionary, received java_env

FATAL: all hosts have already failed -- aborting

**Comment by okoliec** [comment]
@brucellino --pls any pointers to solving this problem. I want to see this installation complete

**Comment by fmarco76** [comment]
It seems the variable java_env is not defined and/or properly initialised in your configuration. You may have a look at the files Debian-servers or CentOS-servers in group_vars directory to see how it can be configured. You have to define the value for the host or in a group containing the host and then run ansible again

**Comment by brucellino** [comment]
Hi  @okoliec  I'm just following up on old tickets - have you managed to solve this ?

**Comment by brucellino** [comment]
Closing this after a week of no response. If the issue arises again, please open another ticket.
