### ISSUE TITLE
IDP metadata url 

### ISSUE THREAD

**Issue by brucellino** [AAROC/DevOps#184]
The IDP metadata url is usually at https://idp.sagrid.ac.za/idp/metadata

however, that is giving a 404.

Now, the IdP metadata url is 
https://idp.sagrid.ac.za/idp/profile/Metadata/SAML

Is this correct ? 

The TERNET idp for example shows nothing on either of these urls. (note, @damas )

**Comment by fmarco76** [comment]
The idp metadata are at 
https://idp.sagrid.ac.za/idp/profile/Metadata/SAML
and
https://idp.sagrid.ac.za/idp/shibboleth

The first url is configured through the handler.xml config file and it refer to a physical file whereas the other is partially depending on a file (I am not sure about this).

Anyway, it is better to providing the file using the handler after the metadata are checked and completed with the missed information
