### ISSUE TITLE
worker nodes playbook yaim Error

### ISSUE THREAD

**Issue by smasoka** [AAROC/DevOps#195]
Error from playbook is: 
 failed: [gnode-2-34] => {"changed": true, "cmd": "/opt/glite/yaim/bin/yaim -c -s /opt/glite/yaim/etc/ZA-CHPC/siteinfo/site-info.def -n MPI_WN -n WN -n TORQUE_client", "delta": "0:08:10.685514", "end": "2015-03-12 09:44:31.436490", "rc": 96, "start": "2015-03-12 09:36:20.750976", "warnings": []}

So i checked the yaim logs for the Error:
WARNING: VO sagrid.ac.za doesn't have pool accounts defined in /opt/glite/yaim/etc/ZA-CHPC/siteinfo/users.conf
   ABORT: Group 'sgmdteam' with gid '1810' for user 'sgmdteam0' failed to be created !
   ERROR: Error when creating a group !
   ERROR: Error when creating a group !

**Comment by brucellino** [comment]
Ok, these are actually two different erros : 

  1. `WARNING: VO sagrid.ac.za doesn't have pool accounts defined in /opt/glite/yaim/etc/ZA-CHPC/siteinfo/users.conf`
  1. `ABORT: Group 'sgmdteam' with gid '1810' for user 'sgmdteam0' failed to be created !`

can you please first confirm which branch you're using (should be `dev`) 

For 1, I will try to reproduce.
For 2, this is a conflct with the uids on your system.

**Comment by smasoka** [comment]
yes, im using the dev repo, I cloned the dev repo. 

Will check number 2 and get back to you.

**Comment by smasoka** [comment]
**Solving number 1**
Kinda solved it self... hahahaha

**Solving number 2**
So ../templates/opt/glite/yaim/etc/siteinfo/users.conf.j2
has this code, which causes group conflicts

for number in range(2) -%}
{{ 18101 + number }}:prddteam{{ number }}:**1810**,1800:prddteam,dteam:dteam:prd
{% endfor -%}

{% for number in range(2) -%}
{{ 18201 + number }}:sgmdteam{{ number }}:{{ **1810 + number**}},1800:sgmdteam,dteam:dteam:sgm
{% endfor -%}
 
"number" ranges from 0-1, so group for prddteam and sgmdteam becomes 1810
I changed for sgmdteam {{ **1811+ number**}} and it worked. 


I also changed roles/common/vars/middleware/igtf.yml
igtf_release_version to the latest version (1.63-1.noarch) since (1.62-1.noarch) is no longer available on the URL.

**Comment by brucellino** [comment]
I just ran into this same issue now. The fix has been applied in f99fab2
