### ISSUE TITLE
Certificate Error in idp-ldap.yml & liferay-csgf.yml 

### ISSUE THREAD

**Issue by Abdelrahman1985** [AAROC/DevOps#198]
Dear All,
after i run the playbook idp-ldap.yml -- i got the following error : 
TASK: [Announce new IdP to the federation manager] ****************************
failed: [idp1.asrenorg.net] => {"failed": true}
msg: Failed to validate the SSL certificate for asrenorg.net:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansibleFATAL: all hosts have already failed -- abortingPLAY RECAP ********************************************************************
          to retry, use: --limit @/root/idp-ldap.retryidp1.asrenorg.net          : ok=66   changed=3    unreachable=0    failed=1
ldap.asrenorg.net          : ok=24   changed=0    unreachable=0    failed=0 

and in playbook liferay-csgf.yml -- i got the following error

TASK: [certificates | Copy host x509 certificate into /etc/grid-security] *****
fatal: [sgw.asrenorg.net] => input file not found at /root/DevOps/Ansible/roles/certificates/files/etc/grid-security/hostcert.pem-idp.asrenorg.net or /root/DevOps/Ansible/etc/grid-security/hostcert.pem-idp.asrenorg.netFATAL: all hosts have already failed -- abortingPLAY RECAP ********************************************************************
          to retry, use: --limit @/root/liferay-csgf.retrysgw.asrenorg.net           : ok=20   changed=14   unreachable=1    failed=0 

please help!

**Comment by Abdelrahman1985** [comment]
@brucellino :)

**Comment by brucellino** [comment]
these are two separate issues, (invalid CA certs and missing certificate)  could you please open one ticket per issue. Thanks  !
