### ISSUE TITLE
Certificate Error in idp-ldap.yml 

### ISSUE THREAD

**Issue by Abdelrahman1985** [AAROC/DevOps#202]
@brucellino 

Dear All,
after i run the playbook idp-ldap.yml -- i got the following error :
TASK: [Announce new IdP to the federation manager] ****************************
failed: [idp1.asrenorg.net] => {"failed": true}
msg: Failed to validate the SSL certificate for asrenorg.net:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansibleFATAL: all hosts have already failed -- abortingPLAY RECAP ********************************************************************
to retry, use: --limit @/root/idp-ldap.retryidp1.asrenorg.net : ok=66 changed=3 unreachable=0 failed=1
ldap.asrenorg.net : ok=24 changed=0 unreachable=0 failed=0

**Comment by brucellino** [comment]
can you check that the root certificate of the Comodo CA is installed on the machine ? It should be `ca-certificates` package.

**Comment by Abdelrahman1985** [comment]
how can i check it?

**Comment by brucellino** [comment]
yum install ca-certificates

**Comment by Abdelrahman1985** [comment]
Package ca-certificates-2014.1.98-65.1.el6.noarch already installed and latest version

**Comment by Abdelrahman1985** [comment]
hi all,
any solution for this problem ?

**Comment by Abdelrahman1985** [comment]
e have re-installed the file “idp-ldap.yml” and we have got the following result:failed: [idp.asrenorg.net] => {"failed": true}
msg:  failed to send payload={"username": "Ansible on idp.asrenorg.net", "text": "A new Shib-IdP has been deployed. Metadata is at https://idp.asrenorg.net/idp/shibboleth. Ask @fmarco76 to check it and add it to the test federation.", "parse": "full", "link_names": 1, "icon_url": "http://www.ansible.com/favicon.ico", "channel": "#webops"} to https://hooks.slack.com/services/[obscured]: HTTP Error 400: BAD_REQUESTSo I think there’s no problem in our configuration , just we should be added by Mr. Marco.

@fmarco76

**Comment by brucellino** [comment]
This is due to the slack_token not being passed. I'll pass it to you on the slack channel.

**Comment by Abdelrahman1985** [comment]
what should i do ?

**Comment by Abdelrahman1985** [comment]
@brucellino 
@fmarco76 
what is the solution for this problem : 
failed: [idp.asrenorg.net] => {"failed": true}
msg: failed to send payload={"username": "Ansible on idp.asrenorg.net", "text": "A new Shib-IdP has been deployed. Metadata is at https://idp.asrenorg.net/idp/shibboleth. Ask @fmarco76 to check it and add it to the test federation.", "parse": "full", "link_names": 1, "icon_url": "http://www.ansible.com/favicon.ico", "channel": "#webops"} to https://hooks.slack.com/services/[obscured]: HTTP Error 400: BAD_REQUESTSo I think there’s no problem in our configuration , just we should be added by Mr. Marco.

should Mr. marco add us to the test federation?

**Comment by brucellino** [comment]
This is just because you didn't pass the proper HTTP header info to slack- you can solve this by adding `-e slack_token="<the token>" to the command line when running the playbook. Use the token that I sent to you in Slack. We keep it quasi-secret  for obvious reasons :)

**Comment by fmarco76** [comment]
The IdP is not providing the metadata so I cannot add to the test federation. The error is before in the workflow. Actually, the installation should not provide any error even if the service is not registered in any federation.

**Comment by Abdelrahman1985** [comment]
now i become this errorfailed: [ldap.asrenorg.net] => {"changed": true, "cmd": ["ldapadd", "-x", "-w", "prolog51254r", "-D", "cn=admin,dc=local", "-H", "ldap:///", "-f", "/tmp/root.ldif"], "delta": "0:00:00.016740", "end": "2015-03-23 13:14:06.500766", "rc": 49, "start": "2015-03-23 13:14:06.484026", "warnings": []}
stderr: ldap_bind: Invalid credentials (49)FATAL: all hosts have already failed -- aborting

**Comment by brucellino** [comment]
@Abdelrahman1985 I'm closing this, since it was originally referring to the CA certs not being installed. Open a new ticket with the LDAP authentication issue that is now being reported. Thanks !
