### ISSUE TITLE
needs_certificate error

### ISSUE THREAD

**Issue by magfathy** [AAROC/DevOps#215]
this error happened when we try to deploy science gatway

![liferay](https://cloud.githubusercontent.com/assets/12183998/7410515/d0cd73d4-ef2f-11e4-9b47-5f298dbe6c68.png)

TASK: [certificates | Copy host x509 certificate into /etc/grid-security] *****
fatal: [vm01.mucsat.sci.eg] => error while evaluating conditional: hostvars['vm01.mucsat.sci.eg'].needs_certificate == 'true'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/liferay-csgf.retry

vm01.mucsat.sci.eg         : ok=19   changed=1    unreachable=1    failed=0

also the command we used to setup was:

#ansible-playbook -i inventories/inventory.mucsat.sci.eg liferay-csgf.yml -v -vvvv

**Comment by brucellino** [comment]
Hello ! 
This looks like you haven't set the needs_certificate variable for the host being configured (vm01.mucsat.sci.eg) This should be done in the inventory - 
`vm01.mucsat.sci.eg needs_certificate='true'`
This is *probably* not documented, so our bad :( Please add the host vars and re-run.

**Comment by brucellino** [comment]
Hi @magfathy - were you able to get around this ? Please let us know.

**Comment by magfathy** [comment]
Hi @brucellino 
yes, we set the needs_certificate variable and fix the error. Thanks

**Comment by brucellino** [comment]
ok, great. I'm going to close this then :) 

**Solution**: set `needs_certificate` in the host_vars or inventory.
