### ISSUE TITLE
SG Playbook Error

### ISSUE THREAD

**Issue by salmaM** [AAROC/DevOps#219]
I have installed liferay on Centos 7 VM.
While executing liferay.csgf playbook, i had an error in task glassfish-install dependencies (RedHat).

The error:

TASK: [glassfish | install dependencies (RedHat)] *****************************
failed: [192.168.195.130] => (item=shibboleth,httpd,lcg-CA,java-1.7.0-openjdk-devel.x86_64,fontpackages-tools,mod_ssl.x86_64,php.x86_64,vim-enhanced.x86_64,fetch-crl) => {"changed": true, "item": "shibboleth,httpd,lcg-CA,java-1.7.0-openjdk-devel.x86_64,fontpackages-tools,mod_ssl.x86_64,php.x86_64,vim-enhanced.x86_64,fetch-crl", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: mirror.tedra.es\n * epel: mirror.uv.es\n * extras: mirror.tedra.es\n * updates: mirror.tedra.es\nResolving Dependencies\n--> Running transaction check\n---> Package shibboleth.x86_64 0:2.5.4-3.2 will be installed\n--> Processing Dependency: xmltooling-schemas(x86-64) >= 1.5.0 for package: shibboleth-2.5.4-3.2.x86_64\n--> Processing Dependency: libcurl-openssl(x86-64) >= 7.21.7 for package: shibboleth-2.5.4-3.2.x86_64\n--> Processing Dependency: opensaml-schemas(x86-64) >= 2.5.0 for package: shibboleth-2.5.4-3.2.x86_64\n--> Processing Dependency: libmemcached.so.2(libmemcached_2)(64bit) for package: shibboleth-2.5.4-3.2.x86_64\n--> Processing Dependency: libsaml.so.8()(64bit) for package: shibboleth-2.5.4-3.2.x86_64\n--> Processing Dependency: liblog4shib.so.1()(64bit) for package: shibboleth-2.5.4-3.2.x86_64\n--> Processing Dependency: libxmltooling-lite.so.6()(64bit) for package: shibboleth-2.5.4-3.2.x86_64\n--> Processing Dependency: libmemcached.so.2()(64bit) for package: shibboleth-2.5.4-3.2.x86_64\n--> Processing Dependency: libxerces-c-3.1.so()(64bit) for package: shibboleth-2.5.4-3.2.x86_64\n--> Processing Dependency: libxml-security-c.so.17()(64bit) for package: shibboleth-2.5.4-3.2.x86_64\n--> Processing Dependency: libxmltooling.so.6()(64bit) for package: shibboleth-2.5.4-3.2.x86_64\n--> Running transaction check\n---> Package libcurl-openssl.x86_64 0:7.42.1-1.1 will be installed\n---> Package liblog4shib1.x86_64 0:1.0.9-3.1 will be installed\n---> Package libsaml8.x86_64 0:2.5.4-3.3 will be installed\n---> Package libxml-security-c17.x86_64 0:1.7.3-3.1 will be installed\n---> Package libxmltooling6.x86_64 0:1.5.4-4.2 will be installed\n---> Package opensaml-schemas.x86_64 0:2.5.4-3.3 will be installed\n---> Package shibboleth.x86_64 0:2.5.4-3.2 will be installed\n--> Processing Dependency: libmemcached.so.2(libmemcached_2)(64bit) for package: shibboleth-2.5.4-3.2.x86_64\n--> Processing Dependency: libmemcached.so.2()(64bit) for package: shibboleth-2.5.4-3.2.x86_64\n---> Package xerces-c.x86_64 0:3.1.1-6.el7 will be installed\n---> Package xmltooling-schemas.x86_64 0:1.5.4-4.2 will be installed\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n", "httpd-2.4.6-31.el7.centos.x86_64 providing httpd is already installed", "lcg-CA-1.63-1.noarch providing lcg-CA is already installed", "java-1.7.0-openjdk-devel-1.7.0.79-2.5.5.1.el7_1.x86_64 providing java-1.7.0-openjdk-devel.x86_64 is already installed", "fontpackages-tools-1.44-8.el7.noarch providing fontpackages-tools is already installed", "mod_ssl-2.4.6-31.el7.centos.x86_64 providing mod_ssl.x86_64 is already installed", "php-5.4.16-23.el7_0.3.x86_64 providing php.x86_64 is already installed", "vim-enhanced-7.4.160-1.el7.x86_64 providing vim-enhanced.x86_64 is already installed", "fetch-crl-3.0.14-1.el7.noarch providing fetch-crl is already installed"]}
msg: Error: Package: shibboleth-2.5.4-3.2.x86_64 (security_shibboleth)
           Requires: libmemcached.so.2()(64bit)
Error: Package: shibboleth-2.5.4-3.2.x86_64 (security_shibboleth)
           Requires: libmemcached.so.2(libmemcached_2)(64bit)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/liferay-csgf.retry

192.168.195.130            : ok=23   changed=1    unreachable=0    failed=1

_________________________________________________________________

I tried installing libmemcached.so.2 on VM; but no package found.

Thanks in advance.

**Comment by brucellino** [comment]
Hi @salmaM, thanks for the report.

This one looks easy. We don't support CentOS7 with this release, only CentOS6.

The only way to get around this is I think to use the different OS.

We do have  plans to support CentOS7, but this hasn't been tested yet.
Thanks!
