### ISSUE TITLE
Error on running ansible-playbook

### ISSUE THREAD

**Issue by damas** [AAROC/DevOps#227]
Dear all,
I am trying to pull changes and re-run the playbook but I am getting an error:

Run a pull;
```bash
Damass-MacBook-Pro:DevOps dmakweba$ git pull
Already up-to-date.
```
Then, playbook;
```bash
Damass-MacBook-Pro:Ansible dmakweba$ ansible-playbook -i inventories/inventory.dit.ac.tz idp-ldap.yml
ERROR: command is not a legal parameter in an Ansible task or handler
Damass-MacBook-Pro:Ansible dmakweba$ 
```
Any assistant please.

Rgds,
Damas

**Comment by brucellino** [comment]
Thanks @damas ! 
First things first -  please confirm your Ansible version. It should be 1.9 or higher. 
Secondly, re-run with verboseness (`-vvv`) and post the output.

**Comment by damas** [comment]
@Bruce,

Damass-MacBook-Pro:Ansible dmakweba$ ansible --version
ansible 1.9

Damass-MacBook-Pro:Ansible dmakweba$ ansible-playbook -i inventories/inventory.dit.ac.tz idp-ldap.yml -vvv
ERROR: command is not a legal parameter in an Ansible task or handler

Damass-MacBook-Pro:Ansible dmakweba$ ansible-playbook -vvv -i inventories/inventory.dit.ac.tz idp-ldap.yml
ERROR: command is not a legal parameter in an Ansible task or handler

Rgds,
Damas

Network Eng | CTO | TERNET
Mob: +255 754|714 464678
Skype: dmakweba
Alt.Email: dmakweba@icloud.com

**Comment by brucellino** [comment]
@damas This seems to be a common problem when the ansible build is corrupt or when older libraries are loaded by mistake. Are you using ansible from a git checkout ? If so, run `sudo python setup.py install` again then log out and in again to get a clean shell. Just confirm whether this solves the problem.

**Comment by brucellino** [comment]
Hi @damas - seems like this comes from using the `stable1.9` version of Ansible - I got similar errors just now. If you are using the git clone, just check out the version `release1.8.4` and install that (using `sudo python setup.py install`. This should solve the problem.
