### ISSUE TITLE
Retrieve ldap server configuration Error

### ISSUE THREAD

**Issue by MohamedFattah** [AAROC/DevOps#230]
Hi all,

We got the following error while executing Ldap command:
ansible-playbook -i inventories/inventory.mucsat.sci.eg idp-ldap.yml -v -vvvv --ask-vault-pass

Error:
failed: [ldap.iricloud.net] => {"changed": false, "cmd": "ldapsearch -Y EXTERNAL -H ldapi:/// -b cn=config", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/idp-ldap.retry
ldap.iricloud.net          : ok=9    changed=0    unreachable=0    failed=1

**Comment by brucellino** [comment]
hi @MohamedFattah Thanks for the report. I can't tell which task this is failing on - please provide the full play output.

thanks !

**Comment by MohamedFattah** [comment]
[root@ansible-controller Ansible]# ansible-playbook -i inventories/inventory.mucsat.sci.eg idp-ldap.yml -v -vvvv --ask-vault-pass
Vault password:

PLAY [Configure the LDAP machine] *********************************************

GATHERING FACTS ***************************************************************
<ldap.iricloud.net> ESTABLISH CONNECTION FOR USER: ansible on PORT 22 TO ldap.iricloud.net
<ldap.iricloud.net> REMOTE_MODULE setup
<ldap.iricloud.net> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434966846.87-217755471735615 && chmod a+rx $HOME/.ansible
/tmp/ansible-tmp-1434966846.87-217755471735615 && echo $HOME/.ansible/tmp/ansible-tmp-1434966846.87-217755471735615'
<ldap.iricloud.net> PUT /tmp/tmpBoPbmN TO /home/ansible/.ansible/tmp/ansible-tmp-1434966846.87-217755471735615/setup
<ldap.iricloud.net> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=mpcrecqrcymamtyqiadjykzegyzujhau] password: " -u
root /bin/sh -c '"'"'echo BECOME-SUCCESS-mpcrecqrcymamtyqiadjykzegyzujhau; LANG=C LC_CTYPE=C /usr/bin/python /home/ansible/.ansible/tmp
/ansible-tmp-1434966846.87-217755471735615/setup; rm -rf /home/ansible/.ansible/tmp/ansible-tmp-1434966846.87-217755471735615/ >/dev/nu
ll 2>&1'"'"''
ok: [ldap.iricloud.net]
ldap.iricloud.net: importing group_vars/passwords-mucsat.yml

TASK: [fmarco76.firewall | Retrieve iptables rules] ***************************
<ldap.iricloud.net> ESTABLISH CONNECTION FOR USER: ansible on PORT 22 TO ldap.iricloud.net
<ldap.iricloud.net> REMOTE_MODULE command iptables -t filter -L -n
<ldap.iricloud.net> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434966851.2-180044793346159 && chmod a+rx $HOME/.ansible/
tmp/ansible-tmp-1434966851.2-180044793346159 && echo $HOME/.ansible/tmp/ansible-tmp-1434966851.2-180044793346159'
<ldap.iricloud.net> PUT /tmp/tmpYYlrCC TO /home/ansible/.ansible/tmp/ansible-tmp-1434966851.2-180044793346159/command
<ldap.iricloud.net> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=agdqrsddmxnsiisbkdjnjtdosgrecjas] password: " -u
root /bin/sh -c '"'"'echo BECOME-SUCCESS-agdqrsddmxnsiisbkdjnjtdosgrecjas; LANG=C LC_CTYPE=C /usr/bin/python /home/ansible/.ansible/tmp
/ansible-tmp-1434966851.2-180044793346159/command; rm -rf /home/ansible/.ansible/tmp/ansible-tmp-1434966851.2-180044793346159/ >/dev/nu
ll 2>&1'"'"''
ok: [ldap.iricloud.net] => {"changed": false, "cmd": ["iptables", "-t", "filter", "-L", "-n"], "delta": "0:00:00.010284", "end": "2015-
06-22 09:54:11.513554", "rc": 0, "start": "2015-06-22 09:54:11.503270", "stderr": "", "stdout": "Chain INPUT (policy ACCEPT)\ntarget
  prot opt source               destination         \nACCEPT     tcp  --  172.14.13.0/24       0.0.0.0/0           state NEW tcp dpt:63
6 \nACCEPT     tcp  --  172.14.13.0/24       0.0.0.0/0           state NEW tcp dpt:389 \n\nChain FORWARD (policy ACCEPT)\ntarget     pr
ot opt source               destination         \n\nChain OUTPUT (policy ACCEPT)\ntarget     prot opt source               destination
        ", "stdout_lines": ["Chain INPUT (policy ACCEPT)", "target     prot opt source               destination         ", "ACCEPT
 tcp  --  172.14.13.0/24       0.0.0.0/0           state NEW tcp dpt:636 ", "ACCEPT     tcp  --  172.14.13.0/24       0.0.0.0/0
   state NEW tcp dpt:389 ", "", "Chain FORWARD (policy ACCEPT)", "target     prot opt source               destination         ", "", "Chain OUTPUT (policy ACCEPT)", "target     prot opt source               destination         "], "warnings": []}
TASK: [fmarco76.firewall | Count iptables rules] ******************************
<ldap.iricloud.net> ESTABLISH CONNECTION FOR USER: ansible on PORT 22 TO ldap.iricloud.net
<ldap.iricloud.net> EXEC $SHELL -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=wlidgifomlvvcfmopqfreulkukwydekf] password: " -u root $SHELL -c '"'"'echo BECOME-SUCCESS-wlidgifomlvvcfmopqfreulkukwydekf; iptables -t filter -S INPUT | grep -v "\-P" | wc -l | tr -d "\n"'"'"''
ok: [ldap.iricloud.net] => {"changed": false, "rc": 0, "stderr": "", "stdout": "2", "stdout_lines": ["2"]}

TASK: [fmarco76.firewall | Apply rules for the local network] *****************
skipping: [ldap.iricloud.net] => (item=389)
skipping: [ldap.iricloud.net] => (item=636)

TASK: [fmarco76.firewall | Apply rules for the defined network] ***************
skipping: [ldap.iricloud.net] => (item=389)
skipping: [ldap.iricloud.net] => (item=636)

TASK: [fmarco76.firewall | Apply nat rules] ***********************************
skipping: [ldap.iricloud.net] => (item=389)
skipping: [ldap.iricloud.net] => (item=636)

TASK: [fmarco76.firewall | Save iptable rules] ********************************
skipping: [ldap.iricloud.net]

TASK: [fmarco76.firewall | Save iptable rules] ********************************
skipping: [ldap.iricloud.net]

TASK: [ldap | what are we installing?] ****************************************
<ldap.iricloud.net> ESTABLISH CONNECTION FOR USER: ansible on PORT 22 TO ldap.iricloud.net
ok: [ldap.iricloud.net] => {
    "msg": "['openldap', 'openldap-servers', 'openldap-clients'] will be installed in /etc/openldap"
}
TASK: [ldap | Install the openldap and required Packages for RedHat] **********
<ldap.iricloud.net> ESTABLISH CONNECTION FOR USER: ansible on PORT 22 TO ldap.iricloud.net
<ldap.iricloud.net> REMOTE_MODULE yum name=openldap,openldap-servers,openldap-clients state=installed
<ldap.iricloud.net> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434966856.36-94788127698039 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1434966856.36-94788127698039 && echo $HOME/.ansible/tmp/ansible-tmp-1434966856.36-94788127698039'
<ldap.iricloud.net> PUT /tmp/tmptG88V3 TO /home/ansible/.ansible/tmp/ansible-tmp-1434966856.36-94788127698039/yum
<ldap.iricloud.net> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=nccjfebufthrrnikhsjvefftdkkylggc] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-nccjfebufthrrnikhsjvefftdkkylggc; LANG=C LC_CTYPE=C /usr/bin/python -tt /home/ansible/.ansible/tmp/ansible-tmp-1434966856.36-94788127698039/yum; rm -rf /home/ansible/.ansible/tmp/ansible-tmp-1434966856.36-94788127698039/ >/dev/null 2>&1'"'"''
ok: [ldap.iricloud.net] => (item=openldap,openldap-servers,openldap-clients) => {"changed": false, "item": "openldap,openldap-servers,openldap-clients", "msg": "", "rc": 0, "results": ["openldap-2.4.39-8.el6.i686 providing openldap is already installed", "openldap-servers-2.4.39-8.el6.x86_64 providing openldap-servers is already installed", "openldap-clients-2.4.39-8.el6.x86_64 providing openldap-clients is already installed"]}

TASK: [ldap | Install the openldap and required Packages for Debian] **********
skipping: [ldap.iricloud.net]

TASK: [ldap | Start ldap server] **********************************************
<ldap.iricloud.net> ESTABLISH CONNECTION FOR USER: ansible on PORT 22 TO ldap.iricloud.net
<ldap.iricloud.net> REMOTE_MODULE service name=slapd state=started enabled=yes
<ldap.iricloud.net> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434966860.22-38172851792133 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1434966860.22-38172851792133 && echo $HOME/.ansible/tmp/ansible-tmp-1434966860.22-38172851792133'
<ldap.iricloud.net> PUT /tmp/tmpjrYfxb TO /home/ansible/.ansible/tmp/ansible-tmp-1434966860.22-38172851792133/service
<ldap.iricloud.net> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=mavsurepsvhmvptdushqhwybhvyztifb] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-mavsurepsvhmvptdushqhwybhvyztifb; LANG=C LC_CTYPE=C /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1434966860.22-38172851792133/service; rm -rf /home/ansible/.ansible/tmp/ansible-tmp-1434966860.22-38172851792133/ >/dev/null 2>&1'"'"''
ok: [ldap.iricloud.net] => {"changed": false, "enabled": true, "name": "slapd", "state": "started"}
TASK: [ldap | Retrieve ldap server configuration] *****************************
<ldap.iricloud.net> ESTABLISH CONNECTION FOR USER: ansible on PORT 22 TO ldap.iricloud.net
<ldap.iricloud.net> REMOTE_MODULE command ldapsearch -Y EXTERNAL -H ldapi:/// -b cn=config
<ldap.iricloud.net> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434966862.35-274307437234909 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1434966862.35-274307437234909 && echo $HOME/.ansible/tmp/ansible-tmp-1434966862.35-274307437234909'
<ldap.iricloud.net> PUT /tmp/tmpWouP67 TO /home/ansible/.ansible/tmp/ansible-tmp-1434966862.35-274307437234909/command
<ldap.iricloud.net> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=taafzhmbxtpicdfqqehkawghqmmnwvgr] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-taafzhmbxtpicdfqqehkawghqmmnwvgr; LANG=C LC_CTYPE=C /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1434966862.35-274307437234909/command; rm -rf /home/ansible/.ansible/tmp/ansible-tmp-1434966862.35-274307437234909/ >/dev/null 2>&1'"'"''
failed: [ldap.iricloud.net] => {"changed": false, "cmd": "ldapsearch -Y EXTERNAL -H ldapi:/// -b cn=config", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/idp-ldap.retry

ldap.iricloud.net          : ok=9    changed=0    unreachable=0    failed=1

**Comment by brucellino** [comment]
Ok, it seems like there is no `cn=config` branch of the ldap server. I assume that this is a brand new install, right ? Can you please confirm the OS version ? 

The LDAP tree looks ok from an unauthenticated view, but it may be that the configuration for your OS version is stored in a different path.

**Comment by MohamedFattah** [comment]
[ansible@ldap ~]$ cat /etc/centos-release
CentOS release 6.6 (Final)

**Comment by brucellino** [comment]
@MohamedFattah Can you please let me know what's under `/etc/openldap/slapd` on your ldap machine  ? 
We properly configured machines should have something like : 

```bash
[root@ldap slapd.d]# ls cn\=config
cn=module{0}.ldif  cn=schema.ldif              olcDatabase={-1}frontend.ldif  olcDatabase={2}bdb
cn=schema          olcDatabase={0}config.ldif  olcDatabase={1}monitor.ldif    olcDatabase={2}bdb.ldif
```

**Comment by MohamedFattah** [comment]
[root@ldap ~]# ls /etc/openldap/slapd.d/cn\=config
cn=module{0}.ldif  cn=schema.ldif              olcDatabase={-1}frontend.ldif  olcDatabase={2}bdb
cn=schema          olcDatabase={0}config.ldif  olcDatabase={1}monitor.ldif    olcDatabase={2}bdb.ldif
