### ISSUE TITLE
Do I need root password for ansible?

### ISSUE THREAD

**Issue by qasims** [AAROC/DevOps#236]
I am sudo user but most of  setting on this repo has root as user. when I run bootstrap.yml with sudo user I get authenticated successfully but it try to install some module but give permission errors on /var/lib/dpkg/ . Do I need root user for ansible?

![image](https://cloud.githubusercontent.com/assets/3830639/8395990/155111c4-1d92-11e5-8c9f-150221fcbf74.png)

**Comment by brucellino** [comment]
hi @qasims - in general, bootstrap tasks run as root, since we assume that there are no other users on the target host and so we have to create them and configure them. To answer your specific problem, please post the output of the play and highlight task that fails. Any changes that you may have made to the playbook would be useful too :)
thanks

**Comment by qasims** [comment]
Please screenshot above. 
One more question I am little confuse, when I run idp-ldap.yml will it install shiboleth idp and tomcat and other stuff itself?

**Comment by brucellino** [comment]
Ok thanks. This _should_ not be happening since all commands should be run as root. Can you confirm for me which user you're connecting as ? Use `ansible-playbook <usual stuff> -vvvv`

Typically, you shouldn't run `ansible-playbook` with sudo - this will confuse the user definitions which we have in the playbooks - but connect to the remote machine as root, putting in the root password. 

Also, it looks like you're running the bootstrap play on the local machine. This is fine, but you should use the `local` connection. Use the `-c local` parameter.

**Comment by qasims** [comment]
It is me as sudo (qasim) as I don't have root user password.

**Comment by brucellino** [comment]
ok - as I mentioned before, please use the `-vvvv` option, so we can see which user ansible is connecting as.

**Comment by qasims** [comment]
PLAY [bootstrap the machines] *************************************************

GATHERING FACTS ***************************************************************
<idp.se.ampr.org> ESTABLISH CONNECTION FOR USER: qasim
<idp.se.ampr.org> REMOTE_MODULE setup
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=6                                                                                                                               0s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteracti                                                                                                                               veAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hos                                                                                                                               tbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10                                                                                                                                idp.se.ampr.org /bin/sh -c 'mkdir -p /tmp/ansible-tmp-1435490873.4-174974606546                                                                                                                               984 && chmod a+rx /tmp/ansible-tmp-1435490873.4-174974606546984 && echo /tmp/ans                                                                                                                               ible-tmp-1435490873.4-174974606546984'
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> PUT /tmp/tmpmKkZ0i TO /tmp/ansible-tmp-1435490873.4-1749746065                                                                                                                               46984/setup
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=6                                                                                                                               0s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteracti                                                                                                                               veAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hos                                                                                                                               tbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10                                                                                                                                idp.se.ampr.org /bin/sh -c 'chmod a+r /tmp/ansible-tmp-1435490873.4-17497460654                                                                                                                               6984/setup'
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=6                                                                                                                               0s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteracti                                                                                                                               veAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hos                                                                                                                               tbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10                                                                                                                                idp.se.ampr.org /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=cn                                                                                                                               ycutvmkgdqxmdhfojhyyryrxermfhj] password: " -u qasim /bin/sh -c '"'"'echo BECOME                                                                                                                               -SUCCESS-cnycutvmkgdqxmdhfojhyyryrxermfhj; LANG=C LC_CTYPE=C /usr/bin/python /tm                                                                                                                               p/ansible-tmp-1435490873.4-174974606546984/setup'"'"''
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=6                                                                                                                               0s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteracti                                                                                                                               veAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hos                                                                                                                               tbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10                                                                                                                                idp.se.ampr.org /bin/sh -c 'rm -rf /tmp/ansible-tmp-1435490873.4-17497460654698                                                                                                                               4/ >/dev/null 2>&1'
EXEC previous known host file not found for idp.se.ampr.org
ok: [idp.se.ampr.org]

TASK: [Send Slack Message] ****************************************************
<idp.se.ampr.org> ESTABLISH CONNECTION FOR USER: qasim
<idp.se.ampr.org> REMOTE_MODULE slack channel='#ssaidp' msg='Starting bootstrap                                                                                                                                on idp.se.ampr.org' token=T06TL7V17/B06U0LDBK/2WFsmJFsNf2vEgelD8yBWh4w parse=ful                                                                                                                               l domain=idp-se-ampr-org.slack.com username='qasim on idp.se.ampr.org'
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=6                                                                                                                               0s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteracti                                                                                                                               veAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hos                                                                                                                               tbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10                                                                                                                                idp.se.ampr.org /bin/sh -c 'mkdir -p /tmp/ansible-tmp-1435490874.78-17030904955                                                                                                                               1878 && chmod a+rx /tmp/ansible-tmp-1435490874.78-170309049551878 && echo /tmp/a                                                                                                                               nsible-tmp-1435490874.78-170309049551878'
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> PUT /tmp/tmpDIglZZ TO /tmp/ansible-tmp-1435490874.78-170309049                                                                                                                               551878/slack
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=6                                                                                                                               0s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteracti                                                                                                                               veAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hos                                                                                                                               tbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10                                                                                                                                idp.se.ampr.org /bin/sh -c 'chmod a+r /tmp/ansible-tmp-1435490874.78-1703090495                                                                                                                               51878/slack'
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=6                                                                                                                               0s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteracti                                                                                                                               veAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hos                                                                                                                               tbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10                                                                                                                                idp.se.ampr.org /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=md                                                                                                                               koeaxkxgqdznkvdzwvdzzgqapjginh] password: " -u qasim /bin/sh -c '"'"'echo BECOME                                                                                                                               -SUCCESS-mdkoeaxkxgqdznkvdzwvdzzgqapjginh; LANG=C LC_CTYPE=C /usr/bin/python /tm                                                                                                                               p/ansible-tmp-1435490874.78-170309049551878/slack'"'"''
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10 idp.se.ampr.org /bin/sh -c 'rm -rf /tmp/ansible-tmp-1435490874.78-170309049551878/ >/dev/null 2>&1'
EXEC previous known host file not found for idp.se.ampr.org
ok: [idp.se.ampr.org] => {"changed": false, "msg": "OK"}

TASK: [bootstrap | check connectivity] ****************************************
<idp.se.ampr.org> ESTABLISH CONNECTION FOR USER: qasim
<idp.se.ampr.org> REMOTE_MODULE command /bin/ping -c 1 www.google.com
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10 idp.se.ampr.org /bin/sh -c 'mkdir -p /tmp/ansible-tmp-1435490876.35-267533651697073 && chmod a+rx /tmp/ansible-tmp-1435490876.35-267533651697073 && echo /tmp/ansible-tmp-1435490876.35-267533651697073'
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> PUT /tmp/tmpiVx9Et TO /tmp/ansible-tmp-1435490876.35-267533651697073/command
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10 idp.se.ampr.org /bin/sh -c 'chmod a+r /tmp/ansible-tmp-1435490876.35-267533651697073/command'
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10 idp.se.ampr.org /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=azscrytsiveijlruokzaclsyzqocaxux] password: " -u qasim /bin/sh -c '"'"'echo BECOME-SUCCESS-azscrytsiveijlruokzaclsyzqocaxux; LANG=C LC_CTYPE=C /usr/bin/python /tmp/ansible-tmp-1435490876.35-267533651697073/command'"'"''
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10 idp.se.ampr.org /bin/sh -c 'rm -rf /tmp/ansible-tmp-1435490876.35-267533651697073/ >/dev/null 2>&1'
EXEC previous known host file not found for idp.se.ampr.org
changed: [idp.se.ampr.org] => {"changed": true, "cmd": ["/bin/ping", "-c", "1", "www.google.com"], "delta": "0:00:00.056096", "end": "2015-06-28 13:27:56.791583", "rc": 0, "start": "2015-06-28 13:27:56.735487", "stderr": "", "stdout": "PING www.google.com (74.125.143.99) 56(84) bytes of data.\n64 bytes from la-in-f99.1e100.net (74.125.143.99): icmp_seq=1 ttl=50 time=9.73 ms\n\n--- www.google.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 9.732/9.732/9.732/0.000 ms", "warnings": []}

TASK: [bootstrap | debug] *****************************************************
<idp.se.ampr.org> ESTABLISH CONNECTION FOR USER: qasim
ok: [idp.se.ampr.org] => {
    "var": {
        "hosttest.stderr": ""
    }
}

TASK: [bootstrap | use Google public DNS if necessary] ************************
skipping: [idp.se.ampr.org]

TASK: [bootstrap | Install prerequisite packages (RedHat)] ********************
skipping: [idp.se.ampr.org]

TASK: [bootstrap | Install some useful packages (RedHat)] *********************
skipping: [idp.se.ampr.org]

TASK: [bootstrap | Install prerequisite packages (Debian)] ********************
<idp.se.ampr.org> ESTABLISH CONNECTION FOR USER: qasim
<idp.se.ampr.org> REMOTE_MODULE apt name=python-simplejson,iptables,iptables-persistent,mlocate,initscripts,openssh-client state=present
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10 idp.se.ampr.org /bin/sh -c 'mkdir -p /tmp/ansible-tmp-1435490877.12-153945919653064 && chmod a+rx /tmp/ansible-tmp-1435490877.12-153945919653064 && echo /tmp/ansible-tmp-1435490877.12-153945919653064'
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> PUT /tmp/tmptFTu40 TO /tmp/ansible-tmp-1435490877.12-153945919653064/apt
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10 idp.se.ampr.org /bin/sh -c 'chmod a+r /tmp/ansible-tmp-1435490877.12-153945919653064/apt'
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10 idp.se.ampr.org /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=xvqbxzqwfarklcweuuagubhkazdomisq] password: " -u qasim /bin/sh -c '"'"'echo BECOME-SUCCESS-xvqbxzqwfarklcweuuagubhkazdomisq; LANG=C LC_CTYPE=C /usr/bin/python /tmp/ansible-tmp-1435490877.12-153945919653064/apt'"'"''
EXEC previous known host file not found for idp.se.ampr.org
<idp.se.ampr.org> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/qasim/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=qasim -o ConnectTimeout=10 idp.se.ampr.org /bin/sh -c 'rm -rf /tmp/ansible-tmp-1435490877.12-153945919653064/ >/dev/null 2>&1'
EXEC previous known host file not found for idp.se.ampr.org
failed: [idp.se.ampr.org] => (item=python-simplejson,iptables,iptables-persistent,mlocate,initscripts,openssh-client) => {"failed": true, "item": "python-simplejson,iptables,iptables-persistent,mlocate,initscripts,openssh-client"}
stderr: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'python-simplejson' 'iptables-persistent'' failed: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/qasim/bootstrap.retry

**Comment by brucellino** [comment]
hi @qasims - 

Two things

  1. Please use markdown when submitting tickets, instead of plain text (see, [Contributing](../blob/master/CONTRIBUTING.md#use-markdown-as-it-was-intended) - this makes it easier for us to read the output :)
  1. As I suspected, ansible is connecting as the user `qasims`. You're executing Ansible as root, but it still reads your default user connection as `qasims`, either from the configuration file or from environment variables. This is actually a good thing, but you need sudo rights in this case. You can fix it by using the `-u root` flags, tellling Ansible to connect as root. 

Remember that the bootstrap role is supposed to be run once-off on completely uninitialised machines. Everything else after that needs to be run in userspace.

**Comment by qasims** [comment]
I tried same command with -u root same result nothing changed same error.
