### ISSUE TITLE
Missing become password

### ISSUE THREAD

**Issue by qasims** [AAROC/DevOps#239]
I am running following command can you please see what is the problem.
```
ansible-playbook -k -u root --ask-vault-pass /etc/ansible/idp-ldap.yml
SSH password:
Vault password:

PLAY [Configure the LDAP machine] *********************************************

GATHERING FACTS ***************************************************************
fatal: [idp.se.ampr.org] => Missing become password

TASK: [fmarco76.firewall | Retrieve iptables rules] ***************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/qasim/idp-ldap.retry

idp.se.ampr.org            : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by brucellino** [comment]
hi @qasims 

Can you check what's in your ansible.cfg under  `ask_sudo_pass`
See 
http://serverfault.com/questions/690644/what-does-localhost-failed-missing-become-password-mean-how-do-i-get-pas/690651#690651

**Comment by brucellino** [comment]
hi @qasims - thanks for closing the ticket :) can you please confirm what the solution was for future reference ? 
Thanks!

**Comment by qasims** [comment]
Yes it  was same issue as you mentioned above I uncommented ask_sudo_passin ansible.cfg started working.
