### ISSUE TITLE
ERROR: multiple actions specified in task: 'service' and 'Restart tomcat'

### ISSUE THREAD

**Issue by okoliec** [AAROC/DevOps#243]
@brucellino 

Just started a new deployment as discussed. I have setup both servers and this is the output of the first ansible-playbook report

```
root@ansible:~/DevOps/Ansible# ansible-playbook -i inventories/inventory.unilag bootstrap.yml 

PLAY RECAP ******************************************************************** 
idp.unilag.edu.ng          : ok=10   changed=1    unreachable=0    failed=0   
ldapnew.unilag.edu.ng      : ok=10   changed=1    unreachable=0    failed=0 
```
When i attempted loading the idp-ldap.yml playbook. I got this error

```
root@ansible:~/DevOps/Ansible# ansible-playbook -i inventories/inventory.unilag idp-ldap.yml 
ERROR: multiple actions specified in task: 'service' and 'Restart tomcat'
```

Any clues
thanks

**Comment by brucellino** [comment]
hi @okoliec 
Thanks for reporting this. Can you please confirm that you are on the `dev` branch ? Which commit are you on ? 
Also, which version of Ansible are you using ?

**Comment by okoliec** [comment]
hello @brucellino 

Yes am on the dev branch.

I started off from a fresh by running this
rm -rf DevOps
git clone https://github.com/AAROC/DevOps
cd DevOps
git checkout dev

Ansible version= Version: 1.8.4-1ppa~trusty

**Comment by brucellino** [comment]
Ok thanks. I'll try to reproduce this. I have a suspicion that your version of Ansible is too old. We are developing for 1.9-stable . If you want to check in the meantime, please follow the install procedure : 

http://docs.ansible.com/intro_installation.html#running-from-source

**Comment by okoliec** [comment]
I will check the link and upgrade. But will checking i commented out this line and the error disappeared. Not sure why

root@ansible:~/DevOps/Ansible# vi roles/fmarco76.IDPPublic/tasks/install.yml
- name: Restart tomcat
  sudo: yes
  #service: name={{ tomcat6_service }}  state=restarted
  #when: tomcat_root_change.changed
  wait_for:
    port: 8443

**Comment by brucellino** [comment]
ah... Thanks, this explains a lot. Keep that commented ; I'll submit a patch in a bit.

**Comment by brucellino** [comment]
tests have passed now.
