### ISSUE TITLE
Push the intermediate and root cert: input file not found

### ISSUE THREAD

**Issue by okoliec** [AAROC/DevOps#256]
@brucellino 
I encountered this error while running idp-ldap playbook.

root@ansible:~/DevOps/Ansible# ansible-playbook -i inventories/inventory.UNILAG idp-ldap.yml

TASK: [shibboleth-idp | extract the subject] ********************************** 
skipping: [idp.unilag.edu.ng]

TASK: [shibboleth-idp | Debug subject] **************************************** 
ok: [idp.unilag.edu.ng] => {
    "{{ subject.stdout | regex_replace('^.*N(.*)$' ) }}": "{{ subject.stdout | regex_replace('^.*N(.*)$' ) }}"
}

TASK: [shibboleth-idp | debug CA certs] *************************************** 
ok: [idp.unilag.edu.ng] => {
    "cert_CA_certificates": "cert_CA_certificates"
}

TASK: [shibboleth-idp | Push the intermediate and root cert] ****************** 
fatal: [idp.unilag.edu.ng] => input file not found at /root/DevOps/Ansible/roles/shibboleth-idp/files/roles/certificates/files/commercial/{# cert_CA_certificates #} or /root/DevOps/Ansible/roles/certificates/files/commercial/{# cert_CA_certificates #}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/idp-ldap.retry

idp.unilag.edu.ng          : ok=24   changed=0    unreachable=1    failed=0   
ldapnew.unilag.edu.ng      : ok=24   changed=0    unreachable=0    failed=0

**Comment by brucellino** [comment]
ah I haven't committed those files yet :unamused:  - hold on. and I will commit them.

**Comment by brucellino** [comment]
ok, the files are there, but the variable is missing: `cert_CA_certificate`
You should add the following to the group_vars of your site : 
```yaml
cert_CA_certificates:
  - COMODORSADomainValidationSecureServerCA.crt
  - AddTrustExternalCARoot.crt
  - COMODORSAAddTrustCA.crt
```

**Comment by okoliec** [comment]
root@ansible:~/DevOps/Ansible# ansible-playbook -i inventories/inventory.UNILAG idp-ldap.yml   

PLAY [Configure the LDAP machine] ********************************************* 

GATHERING FACTS *************************************************************** 
ok: [ldapnew.unilag.edu.ng]
ldapnew.unilag.edu.ng: importing group_vars/passwords-UNILAG.yml

TASK: [fmarco76.firewall | Retrieve iptables rules] *************************** 
ok: [ldapnew.unilag.edu.ng]

TASK: [fmarco76.firewall | Count iptables rules] ****************************** 
ok: [ldapnew.unilag.edu.ng]

TASK: [fmarco76.firewall | Apply rules for the local network] ***************** 
skipping: [ldapnew.unilag.edu.ng] => (item=389)
skipping: [ldapnew.unilag.edu.ng] => (item=636)

TASK: [fmarco76.firewall | Apply rules for the defined network] *************** 
skipping: [ldapnew.unilag.edu.ng] => (item=389)
skipping: [ldapnew.unilag.edu.ng] => (item=636)

TASK: [fmarco76.firewall | Apply nat rules] *********************************** 
skipping: [ldapnew.unilag.edu.ng] => (item=389)
skipping: [ldapnew.unilag.edu.ng] => (item=636)

TASK: [fmarco76.firewall | Save iptable rules] ******************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [fmarco76.firewall | Save iptable rules] ******************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | what are we installing?] **************************************** 
ok: [ldapnew.unilag.edu.ng] => {
    "msg": "['slapd', 'ldap-utils'] will be installed in /etc/ldap"
}

TASK: [ldap | Install the openldap and required Packages for RedHat] ********** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Install the openldap and required Packages for Debian] ********** 
ok: [ldapnew.unilag.edu.ng] => (item=slapd,ldap-utils)

TASK: [ldap | Start ldap server] ********************************************** 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Retrieve ldap server configuration] ***************************** 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Copy modules file LDIF] ***************************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Add modules (Debian)] ******************************************* 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Add modules (RedHat)] ******************************************* 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Restart ldap server] ******************************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Create db LDIF] ************************************************* 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Customise DB] *************************************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Copy Password Policy Schema ldap server (Debian)] *************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Apply ppolicy schema] ******************************************* 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Copy Overlay LDIF] ********************************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Apply overlays] ************************************************* 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Enable Secure Communications with the LDAP server (RedHat)] ***** 
skipping: [ldapnew.unilag.edu.ng] => (item=SLAPD_LDAPI)
skipping: [ldapnew.unilag.edu.ng] => (item=SLAPD_LDAPS)

TASK: [ldap | Enable protocols in sysconfig startup script (RedHat)] ********** 
skipping: [ldapnew.unilag.edu.ng] => (item=SLAPD_LDAPI)
skipping: [ldapnew.unilag.edu.ng] => (item=SLAPD_LDAPS)

TASK: [ldap | Enable Secure Communications with the LDAP server] ************** 
ok: [ldapnew.unilag.edu.ng] => (item=SLAPD_SERVICES)

TASK: [ldap | Create the directory for ldap certificates] ********************* 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Generate the private key for certificate request] *************** 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Strip the passphrase from the key] ****************************** 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Create and sign the the new certificate] ************************ 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Copy secure config (RedHat)] ************************************ 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Copy secure config (Debian)] ************************************ 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Config certificates] ******************************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Restart ldap server] ******************************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Retrieve ldap root dn] ****************************************** 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Create the root node] ******************************************* 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Add the root node] ********************************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Retrieve ldap orgs] ********************************************* 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Create Organisations LDIF] ************************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Add Organisations to the server] ******************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Retrieve ldap default policy] *********************************** 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Copy Default policies] ****************************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Apply overlays] ************************************************* 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Retrieve ldap user] ********************************************* 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Create the first user ldif] ************************************* 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Add first user to ou=People] ************************************ 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Retrieve ldap useradmin] **************************************** 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Create the useradmin ldif] ************************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Add first user to ou=People] ************************************ 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Retrieve ldap services] ***************************************** 
ok: [ldapnew.unilag.edu.ng]

TASK: [ldap | Create the services group] ************************************** 
skipping: [ldapnew.unilag.edu.ng]

TASK: [ldap | Configure the services group] *********************************** 
skipping: [ldapnew.unilag.edu.ng]

PLAY [Deploy Shibboleth IdP and Web Interface] ******************************** 

GATHERING FACTS *************************************************************** 
ok: [idp.unilag.edu.ng]

TASK: [fmarco76.firewall | Retrieve iptables rules] *************************** 
ok: [idp.unilag.edu.ng]

TASK: [fmarco76.firewall | Count iptables rules] ****************************** 
ok: [idp.unilag.edu.ng]

TASK: [fmarco76.firewall | Apply rules for the local network] ***************** 
skipping: [idp.unilag.edu.ng] => (item={'dport': 8080, 'port': 80})

TASK: [fmarco76.firewall | Apply rules for the defined network] *************** 
skipping: [idp.unilag.edu.ng] => (item={'dport': 8080, 'port': 80})

TASK: [fmarco76.firewall | Apply nat rules] *********************************** 
skipping: [idp.unilag.edu.ng] => (item={'dport': 8080, 'port': 80})

TASK: [fmarco76.firewall | Save iptable rules] ******************************** 
skipping: [idp.unilag.edu.ng]

TASK: [fmarco76.firewall | Save iptable rules] ******************************** 
skipping: [idp.unilag.edu.ng]

TASK: [fmarco76.firewall | Retrieve iptables rules] *************************** 
ok: [idp.unilag.edu.ng]

TASK: [fmarco76.firewall | Count iptables rules] ****************************** 
ok: [idp.unilag.edu.ng]

TASK: [fmarco76.firewall | Apply rules for the local network] ***************** 
skipping: [idp.unilag.edu.ng] => (item=80)
skipping: [idp.unilag.edu.ng] => (item=8080)

TASK: [fmarco76.firewall | Apply rules for the defined network] *************** 
skipping: [idp.unilag.edu.ng] => (item=80)
skipping: [idp.unilag.edu.ng] => (item=8080)

TASK: [fmarco76.firewall | Apply nat rules] *********************************** 
skipping: [idp.unilag.edu.ng] => (item=80)
skipping: [idp.unilag.edu.ng] => (item=8080)

TASK: [fmarco76.firewall | Save iptable rules] ******************************** 
skipping: [idp.unilag.edu.ng]

TASK: [fmarco76.firewall | Save iptable rules] ******************************** 
skipping: [idp.unilag.edu.ng]

TASK: [fmarco76.tomcat | Install Java platform and server on the machine (Debian)] *** 
skipping: [idp.unilag.edu.ng]

TASK: [fmarco76.tomcat | Install Java platform and server on the machine (RedHat)] *** 
ok: [idp.unilag.edu.ng] => (item=java-1.7.0-openjdk,java-1.7.0-openjdk-devel,tomcat6,ant,ant-apache-regexp,expect)

TASK: [shibboleth-idp | Download the shibboleth package] ********************** 
ok: [idp.unilag.edu.ng]

TASK: [shibboleth-idp | Create the shibboleth installation directory] ********* 
ok: [idp.unilag.edu.ng]

TASK: [shibboleth-idp | Unpack the tarball] *********************************** 
skipping: [idp.unilag.edu.ng]
ok: [idp.unilag.edu.ng]

TASK: [shibboleth-idp | Copy the installer] *********************************** 
ok: [idp.unilag.edu.ng]

TASK: [shibboleth-idp | Install the package] ********************************** 
ok: [idp.unilag.edu.ng]

TASK: [shibboleth-idp | Associate the correct owner] ************************** 
ok: [idp.unilag.edu.ng]

TASK: [shibboleth-idp | Check if there is a certificate locally] ************** 
ok: [idp.unilag.edu.ng -> 127.0.0.1]

TASK: [shibboleth-idp | Check if there is a key locally] ********************** 
ok: [idp.unilag.edu.ng -> 127.0.0.1]

TASK: [shibboleth-idp | Define certificate status] **************************** 
ok: [idp.unilag.edu.ng -> 127.0.0.1]

TASK: [shibboleth-idp | What is cert status ?] ******************************** 
ok: [idp.unilag.edu.ng] => {
    "cert": "False"
}

TASK: [shibboleth-idp | Debug have cert] ************************************** 
ok: [idp.unilag.edu.ng] => (item=cert) => {
    "have_cert.stat.exists": "False", 
    "item": "cert"
}
ok: [idp.unilag.edu.ng] => (item=key) => {
    "have_key.stat.exists": "False", 
    "item": "key"
}

TASK: [shibboleth-idp | extract the subject] ********************************** 
skipping: [idp.unilag.edu.ng]

TASK: [shibboleth-idp | Debug subject] **************************************** 
ok: [idp.unilag.edu.ng] => {
    "{{ subject.stdout | regex_replace('^.*N(.*)$' ) }}": "{{ subject.stdout | regex_replace('^.*N(.*)$' ) }}"
}

TASK: [shibboleth-idp | debug CA certs] *************************************** 
ok: [idp.unilag.edu.ng] => {
    "cert_CA_certificates": "cert_CA_certificates"
}

TASK: [shibboleth-idp | Push the intermediate and root cert] ****************** 
fatal: [idp.unilag.edu.ng] => input file not found at /root/DevOps/Ansible/roles/shibboleth-idp/files/roles/certificates/files/commercial/{# cert_CA_certificates #} or /root/DevOps/Ansible/roles/certificates/files/commercial/{# cert_CA_certificates #}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/idp-ldap.retry

idp.unilag.edu.ng          : ok=24   changed=0    unreachable=1    failed=0   
ldapnew.unilag.edu.ng      : ok=24   changed=0    unreachable=0    failed=0

**Comment by brucellino** [comment]
Hi

We dropped the ball on this one.  I'm closing this in the meantime, since it's obsolete.
Please open a new issue if the problem arises again.
