### ISSUE TITLE
New user registration on IDPOPEN

### ISSUE THREAD

**Issue by okoliec** [AAROC/DevOps#259]
Dear All,

I just observed that the new IdP I installed returns this mail with the above subject. 

I searched for the file and found it in this path. Since its a binary file can i make the changes to reflect the IdP.

WEB-INF/classes/it/infn/ct/security/actions/ConfirmRegistration.class

See body of the mail
comes with the above subject when
A new registration performed on IDPOPEN,

the user Bruce Becker (bbecker@csir.co.za) from CSIR (ZA)

is waiting for authorisation

**Comment by brucellino** [comment]
Thanks @okoliec 
these changes need to be made to the source code in the package (IDPOpen) , before it is compiled and the WAR deployed. We simply forgot to implement this in the playbook :blush: Will get on it soon.

**Comment by fmarco76** [comment]
Hi All,

I have just opened an issue in my source code for this: https://github.com/osct/IDPPublic/issues/7

It need some change in the source and after we can add the customisation here. Actually, I am not sure about the time to fix it (holiday period) so if you need to customise the mail then you can clone the repo https://github.com/AAROC/IDPPublic, modify, compile and replace the class file. If you can do the change moving the mail text outside of the source then a pull request would be very welcome :).

**Comment by brucellino** [comment]
Thanks @fmarco76 Putting this on hold until we get the PR from you.

**Comment by brucellino** [comment]
hi all.
I'm going through old tickets. this one seems obsolete, since there is a new idopen release out. @okokiec you can open another ticket with the new information if this is still a problem.
