### ISSUE TITLE
it.infn.ct.security.actions.MailException: Mail message has problems

### ISSUE THREAD

**Issue by okoliec** [AAROC/DevOps#261]
@fmarco76 
I just deployed the IdP for WACREN and the registration page seems to have a problem. https://openidp.wacren.net/register

The deployment was successful without any errors except that the registration page returns an error after a user completes the registration page and hit the register button. Please how can i fix this.
Below  is the error

HTTP Status 500 -

it.infn.ct.security.actions.MailException: Mail message has problems
	it.infn.ct.security.actions.AddUser.sendMail(AddUser.java:385)
	it.infn.ct.security.actions.AddUser.execute(AddUser.java:72)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:453)

**Comment by brucellino** [comment]
hi @okoliec - can you please tell us what branch you're using. (`git status`).I'm assigning this to @fmarco76. You can help a lot in the meantime, but trying to find a similar issue on StackOverflow and report here.

**Comment by okoliec** [comment]
Hello @brucellino - 
root@ansible:~/DevOps_WACREN/Ansible# git status
On branch dev
Your branch is ahead of 'origin/dev' by 4 commits.
  (use "git push" to publish your local commits)

**Comment by brucellino** [comment]
hm. what are these 4 commits that you're ahead of us by ? Probably a red-herring, but perhaps might be important. I still think you should try to nail down what the error 
```
it.infn.ct.security.actions.MailException: Mail message has problems
``` 
means. The code in question is not in this repo, but in https://github.com/AAROC/IDPPublic so we might move this issue over  there.

**Comment by okoliec** [comment]
Nothing really to worry about

	modified:   roles/fmarco76.IDPPublic/tasks/install.yml-- commented out the line preventing tomcat from restarting during installation
	modified:   roles/shibboleth-idp/vars/main.yml----Added the wacren federation metadata
	modified:   test.p12----not sure of this

**Comment by brucellino** [comment]
ok, so we need to know from @fmarco76 which logs to check.

**Comment by fmarco76** [comment]
Hi @brucellino and @okoliec, I am not sure if the problem is with IDPPublic or DevOps. Could you search the error in tomcat logs and post here. From your first post there is not the full stacktrace.

You should find the error (or generate a new one) and see tomcat logs in /var/log/tomcat (I am not sure about the location). In the stack trace you should find someting like "Caused by .........." the the method generating the exception.

There are not enough information here to fix the problem
.

**Comment by okoliec** [comment]
@fmarco76 - looking at the logs again. This is all i see

Sep 11, 2015 2:39:01 PM org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap
SEVERE: A web application created a ThreadLocal with key of type [null] (value [com.opensymphony.xwork2.inject.ContainerImpl$10@7e101230]) and a value of type [java.lang.Object[]] (value [[Ljava.lang.Object;@6159c8e3]) but failed to remove it when the web application was stopped. To prevent a memory leak, the ThreadLocal has been forcibly removed.
Sep 11, 2015 2:39:01 PM org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap
SEVERE: A web application created a ThreadLocal with key of type [null] (value [com.opensymphony.xwork2.inject.ContainerImpl$10@7e101230]) and a value of type [java.lang.Object[]] (value [[Ljava.lang.Object;@4d93e103]) but failed to remove it when the web application was stopped. To prevent a memory leak, the ThreadLocal has been forcibly removed.
Sep 11, 2015 2:39:01 PM org.a

**Comment by fmarco76** [comment]
The error is generated in this code:

https://github.com/AAROC/IDPPublic/blob/master/src/java/it/infn/ct/security/actions/AddUser.java#L352-L386

There are 4 methods that could generate the exception

The majority of the parameters in the mail come from the file struts.xml:

https://github.com/AAROC/IDPPublic/blob/master/src/java/struts.xml#L89-L115


It seems there is some thing wrong with this configuration. Can you verify and/or post the configuration of this action in your struts.xml?

**Comment by kodion** [comment]
Yes there was.   For some reason, the mail_contact variable was not updated
from the group_vars.    All is fine now.  We can close this issue.  thanks
