### ISSUE TITLE
Identity provider website error

### ISSUE THREAD

**Issue by MohamedFattah** [AAROC/DevOps#277]
Dear All

We encountered this error while running idp-ldap playbook; idp website doesn't work, although the installation is finished successfully and also mete-data file is created: 

TASK [Announce new IdP to the federation manager] ******************************
task path: /root/DevOps/Ansible/idp-ldap.yml:20
.
.
.
ok: [idp.iricloud.net.eg] => {"changed": false, "invocation": {"module_args": {"channel": "#webops", "domain": "africa-arabia-roc.slack.
 "A new Shib-IdP has been deployed. Metadata is at https://idp.iricloud.net.eg/idp/shibboleth. Ask @fmarco76 to check it and add it to t
: "full", "token": "8lZBc9s71KL8yM3CJQuy84DC", "username": "Ansible on idp.iricloud.net.eg"}, "module_name": "slack"}, "msg": "OK"}

Any solution or recommendation?.

**Comment by brucellino** [comment]
hi @MohamedFattah thanks for reporting this. We usually see the announcements in the slack instance, so the announcement is working.

The link that is announced (https://idp.iricloud.net.eg/idp/shibboleth) is indeed not responding, so something is going wrong. Can you confirm your inventory and `group_variables` please - are they in the repo or modified privately ?

**Comment by MohamedFattah** [comment]
hi @brucellino 
Our group_variables (identity.iricloud) as the following:
---
# Certificate information
# #  which CA issued the certificate
cert_CA: EG-GRID
# # this is the list of the root and intermediate certificates of the CA
# # should probably give these keys names...
cert_CA_certificates:
  - EG-GRID.crt
#
# institute metadata
site_name: iricloud
host_institute:
  name: Informatics Research Institute
  url: http://www.iricloud.net.eg

# 3. LDAP variables

server_country: EG
server_state: Alex
server_location: Alexandria
server_organization: IRICLOUD
server_organization_unit: IRI

ldap_server: ldap.iricloud.net.eg
root_password_clear: OurPass

# 4. Identity provider variables
organisation:
  name: IRI
  logo: iri.jpg

  mail_contact: sgw-iri@iricloud.net.eg

# IDP variables. these are specifically related to the IdPOpen Web front end.
idp:
  name: IRI Cloud Identity Provider
  admin_user: IRIAdmin
  admin_email: sgw-iri@iricloud.net.eg
                                                                                                                      1,1           Top
############################ END #########################
Our inventory (inventory.iricloud.net.eg) as the following:
----------
[ldap-servers]
ldap.iricloud.net.eg needs_certificate=true

[shibboleth-idps]
idp.iricloud.net.eg needs_certificate=true

[science-gateways]
sgw.iricloud.net.eg needs_certificate=true min_jvm_size=1024m max_jvm_size=2048m db-server=192.168.8.93  needs_certificate=true

[db-servers]
192.168.8.93  needs_certificate=true

[CentOS-servers:children]
ldap-servers
shibboleth-idps
science-gateways
db-servers

[identity.iricloud:children]
ldap-servers
shibboleth-idps
############################ END #########################

They are modified privately.
--
On the other hand, it is noticed that meta-data file open when use only http (http://idp.iricloud.net.eg/idp/shibboleth).

**Comment by MohamedFattah** [comment]
hi @brucellino 
These are the logs files related to the problem for your reference.
[logs.txt](https://github.com/AAROC/DevOps/files/106517/logs.txt)

**Comment by MohamedFattah** [comment]
hi @brucellino 
Do you need more information?.

**Comment by MohamedFattah** [comment]
hi @brucellino 
Any idea?

**Comment by brucellino** [comment]
Hi @MohamedFattah  I'm closing this issue since we have a new role for shibboleth v3. 
Sorry for leaving it so long !
