### ISSUE TITLE
TERNET IDP Cant login

### ISSUE THREAD

**Issue by dmakweba** [AAROC/DevOps#334]
#  Issue type

You can't login direct to TERNET IDP at https://idp.ternet.or.tz with an error  invalid username or password is wrong, you cant also using it to access other federated services like SG or forum at sci-GaIA with an error Login has failed. Double-check your username and password.

How would you best describe your issue  ?

  - [x] Problem with one of the services
  - [ ] Ansible problem
  - [ ] Puppet problem
  - [ ] Container problem
  - [ ] Want to join as collaborator
  - [ ] General question, enhancement or suggestion

Please suggest a tag to the issue from the list provided, if relevant.

# Repository information

Unfortunately this was the earlier manual deployment before the use of automation tools like ansible etc, and so I don't have any repository version, instead here are for ;
shibboleth-identityprovider is 2.4.1 and tomcat is 6

  * Branch: null
  * git hash: null

# Issue description
Something unknown and not common happened to IdP whereby it sounded at the browser to have no valid certificate, it was showing expired certificate since 2015 which was not correct because we have the certificate issued by comodo which will expire 2017,unfortunately one of my colleague installed some other open source certificate (something like Let's Encrypt) but I restored the comodo certificate after a week once I realized to have wrong certificate.

The issue might be related to the comodo certificate, metadata or web server (tomcat).

# Logs and other information
1) Catalina logs has the following output with a details of "unable to find valid certification path to requested target", this logs happened when trying to login.
 [root@idp ~]# tail /var/log/tomcat6/catalina.out
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1454)
	... 85 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
	... 91 more

[root@idp ~]#

2) shibboleth logs has the following details;

[root@idp ~]# tail /opt/shibboleth-idp/logs/idp-process.log 
07:33:10.558 - INFO [Shibboleth-Access:73] - 20160804T043310Z|193.206.208.227|idp.ternet.or.tz:443|/profile/Metadata/SAML|
07:38:09.848 - INFO [Shibboleth-Access:73] - 20160804T043809Z|193.206.208.227|idp.ternet.or.tz:443|/profile/Metadata/SAML|
07:43:10.439 - INFO [Shibboleth-Access:73] - 20160804T044310Z|193.206.208.227|idp.ternet.or.tz:443|/profile/Metadata/SAML|
07:45:37.357 - INFO [Shibboleth-Access:73] - 20160804T044537Z|41.93.45.25|idp.ternet.or.tz:443|/profile/SAML2/Redirect/SSO|
07:48:10.745 - INFO [Shibboleth-Access:73] - 20160804T044810Z|193.206.208.227|idp.ternet.or.tz:443|/profile/Metadata/SAML|
07:53:10.049 - INFO [Shibboleth-Access:73] - 20160804T045310Z|193.206.208.227|idp.ternet.or.tz:443|/profile/Metadata/SAML|
07:58:10.592 - INFO [Shibboleth-Access:73] - 20160804T045810Z|193.206.208.227|idp.ternet.or.tz:443|/profile/Metadata/SAML|
08:03:10.369 - INFO [Shibboleth-Access:73] - 20160804T050310Z|193.206.208.227|idp.ternet.or.tz:443|/profile/Metadata/SAML|
08:08:10.476 - INFO [Shibboleth-Access:73] - 20160804T050810Z|193.206.208.227|idp.ternet.or.tz:443|/profile/Metadata/SAML|
08:13:10.654 - INFO [Shibboleth-Access:73] - 20160804T051310Z|193.206.208.227|idp.ternet.or.tz:443|/profile/Metadata/SAML|
[root@idp ~]#

**Comment by brucellino** [comment]
Hi @dmakweba thanks for reporting the  @issue.

Please try to use the playbooks and keep your site information up to date in the repo, this will help us  to avoid mishaps and ensure that the services are working. 

This certainly sounds like there is a problem with the certificate - more precisely the certificate chain.

If this is the case, you need to check that the certificate chain is properly created, and that this is properly used by the tomcat server.

The template which takes care of  this is  is in `Ansible/roles/shibboleth-idp/temmplates/server-{{ ansible_os_family }}.j2`, for example 

https://github.com/AAROC/DevOps/blob/master/Ansible/roles/shibboleth-idp/templates/server-RedHat.xml.j2

Here, the relevant snippet is : 

```xml
 <Connector port="8443"
           protocol="org.apache.coyote.http11.Http11Protocol"
           SSLImplementation="edu.internet2.middleware.security.tomcat6.DelegateToApplicationJSSEImplementation"
           scheme="https"
           SSLEnabled="true"
           ciphers="TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA"
           clientAuth="false"
           keystoreFile="{{ tomcat6_config_path }}/domain.keystore"
           keystorePass="{{ keystore_password }}" />
```

You can see that there are a few variables there, identified by the "{{ }}". These are kept in role vars, and in the group vars. 

This is templated in the `tomcat-confg.yml` task : 
```yml
- name: Enable the ssl
  become: yes
  template:
    src: "server-{{ ansible_os_family }}.xml.j2"
    dest: "{{ tomcat6_config_path }}/server.xml"
  notify: restart tomcat
```

So, first  check the `server.xml` :  Is the keystore properly set ?

If so, the certificate chain : 

`keytool -list <keystore file>`

The tasks in [certificate.yml](../blob/master/Ansible/roles/shibboleth-idp/tasks/certificate.yml) show how to do this.

**Comment by fmarco76** [comment]
Hi @dmakweba,

I am back at office (till tomorrow).
Do you still have the error? If yes, you have to see the full stack trace to identify the service url generating the problem, is that correct? Is the service specified in your configuration files?
If they are different try to restart tomcat and try again.

It seems you have a communication problem with a remote service but we need to understand which service you cannot access first.

**Comment by brucellino** [comment]
thanks @fmarco76 for chiming in. @dmakweba if your log output is large, please put it in a gist and give us the link in your reply to this ticket. You can make a gist at https://gist.github.com/

**Comment by dmakweba** [comment]
Thanks @brucellino @fmarco76 
If I can add from what I have already reported especially to what Marco asked, we can access/login at http://discourse.sci-gaia.eu/ or http://sgw.africa-grid.org/ using our TERNET IDP. It responded with an "opensaml::FatalProfileException" with this details at the bottom: Message was signed, but signature could not be verified.
Too bad even login direct at https://idp.ternet.or.tz gives an error Invalid username or Password is wrong.
So, this is stranger to me as I think we have problem with certificates, because the IDP and LDAP servers can communicate when you test running ldasearch from IDP server you will get details from LDAP server....this is my guess.
Any clue.
Rgds,

**Comment by brucellino** [comment]
@dmakweba ok, if your manual connection check works then you should check if you are using the right configuration in the attributes resolver config file. The two errors seem like they point to two different things: 

```
"opensaml::FatalProfileException" 
Message was signed, but signature could not be verified.
``` 
This points to a  misconfigured certificate or keychain

The invalid username or password points to an invalid attribute resolver configuration. 

I would like to keep the issues separate : **Could you please open a new ticket with the ldap problem**, so that we can keep this issue related to the certificate store ?

Thanks !

**Comment by brucellino** [comment]
hi @dmakweba - we are still waiting for a reply o this. Can you tell us if the certificate problem has been resolved and if you opened a new ticket for the ldap problem ?

**Comment by dmakweba** [comment]
Hi @brucellino - my apology for not responding your message. We still have a problem with our IDP as described earlier, we cant login straight at https://idp.ternet.or.tz or even to services like sci-gaia forum.
I will open another ticket for LDAP.

**Comment by brucellino** [comment]
hi @dmakweba - @fmarco76 and I have just checked the idp from the inside. the LDAP connection is working ok. The attribute resolver (ie, communication between the idp and the sp) is working ok. We are checking the login.conf.

**Comment by brucellino** [comment]
@dmakweba  we are now back to the metadata issue we saw here https://github.com/AAROC/DevOps/issues/334#issuecomment-238149276.  @fmarco76 is taking a look at the metadata exchange to see what the issue could be.

**Comment by brucellino** [comment]
ok, we have probably solved the issue. The problem was that you changed the host certificate, but didn't update the shibboleth configuration. This has been done.

**Comment by brucellino** [comment]
We're waiting for the metadata to updated in the federation. Then, we will test and close.

**Comment by dmakweba** [comment]
Thanks team.
I am Stil also concerning why we can't even login directly? Error: "Invalid username or password is wrong"
ciao

**Comment by brucellino** [comment]
Yes, this we have been able to reproduce. This is something in the configuration of the IDPPublic application, and has nothing to do with shibboleth or the SP<->IDP problem. We will get to that as soon as we can ensure that the login to services using the idp is working.

**Comment by brucellino** [comment]
Ok, I have checked that we can log in. the metadata issue has been solved, but the attribute filter is not returning the `eppn` of the user, so we get the famous : 

```
Your Identity Provider has authenticated your account but the SAML assertion does not include the attributes needed by Discourse to let you in. Please contact your Identity Provider administrator and ask to release the following attribute:

    eduPersonPrincipalName (mandatory)
    mail (mandatory)
    sn (optional)
    givenName (optional)
```

however, since we still have problems with logging in directly to the idp, I won't close the ticket yet.

**Comment by brucellino** [comment]
Ok, we have solved the problem. There were several misconfigurations in the web application and in apache configuration. Note: what we found was a "nonstandard" configuration, which is fine, but not supported. so, we have reverted the configuration back to the "standard" one which is implemented by the playbook.

# Summary 

  1. The LDAP configuration was fine in the shibboleth idp configuration, but the ldap server was incorrectly set for the idppublic tomcat web application. 
  1. The tomcat web application was deployed into /IDPPublic instead of ROOT and 
  1. There was a reverse proxy in the Apache configuration which redirected requests to / to /IDPPublic, thereby using the wrong ldap configuration.

**Comment by brucellino** [comment]
This issue was moved to http://discourse.sci-gaia.eu/t/ternet-idp-cant-login/2296
