### ISSUE TITLE
Error authenticating with idp.kenet.or.ke

### ISSUE THREAD

**Issue by sureronald** [AAROC/DevOps#336]
I am getting the error in the attached image when I try to join the conversation at http://discourse.sci-gaia.eu using the KENET idp in subject.
Now this is an old IDP that was setup during the mailing list collaborations. Just before I attach any logs I just wanted to know if it should be able to work in the current Federated environment.
![screenshot from 2016-08-22 12 16 11](https://cloud.githubusercontent.com/assets/577803/18115601/47053ccc-6f49-11e6-9137-3f2970712223.png)

**Comment by fmarco76** [comment]
Hi,

the IdP should work properly. From the message the error could be:
- the server time is wrong
- the certificate configured in the idp is different from the one in the metadata.

Could you verify? If both are correct then we have to check the logs of the IdP and SP.

Cheers,
Marco

**Comment by sureronald** [comment]
Thanks for the pointers. I will check and update

**Comment by mngmuia** [comment]
I have checked the server time and it is okay.

See root@idp:/opt/shibboleth-idp/credentials# date
Wed Sep  7 10:27:04 EAT 2016

I have also inspected the server certificate and the certificate on the meta data at /opt/shibboleth-idp/metadata/idp-metadata.xml

Note that login to the Africa science gateway works! Is there specific config that needs to be added for the forum to work?

Regards,
Peter Muia

**Comment by brucellino** [comment]
Hi @mngmuia, 

Thanks for the confirmation. If tbe login works with the sgw, then i suspect that it is the attribute scoping, right, @fmarco76?

Can you remind peter where this is set in the metadata?

**Comment by muokid3** [comment]
Hi @brucellino and @fmarco76  just to add, am getting the exact same error like @mngmuia

**Comment by brucellino** [comment]
Thanks @muokid3 
We've put this issue into "in progress". There may be an issue with stale metadata on the discourse server (ie, "our side"). We are trying to eliminate possibilities at the moment.

**Comment by brucellino** [comment]
Ok, we have found the problem. It is a problem on the discourse shibboleth metadata side. There was an old certificate specified in the gridp-test metadata. The KENET IdP is both in the gridp-test and the gridp federations, however it's metadata was being found first in gridp-test. For this reason, we were not able to verify the certificate name, since the federation contained the old certificate public key. 

the fix was to remove the kenet id from gridp-test.

**Comment by brucellino** [comment]
I have tested the fix, it solves this problem - but raises another -the famous "missing eppn" issue : 

```
Your Identity Provider has authenticated your account but the SAML assertion does not include the attributes needed by Discourse to let you in. Please contact your Identity Provider administrator and ask to release the following attribute:

    eduPersonPrincipalName (mandatory)
    mail (mandatory)
    sn (optional)
    givenName (optional)
```
