### ISSUE TITLE
Puppet cvmfs submodule

### ISSUE THREAD

**Issue by brucellino** [AAROC/DevOps#341]
The puppet manifest for deploying and connfiguring CVMFS repos (stratum 0 and Stratum1) should be added as a git submodule to the DevOps Repo.

**Comment by bazinski** [comment]
except i dont want to do submodules for reasons of r10k, but that is a bigger subject than this.

**Comment by brucellino** [comment]
Are you using the DevOps repo to r10k ? I was under the impression that you weren't - but we still need to have eyes on the code that we're using to deploy services. I can see  that this is  not a trivial issue, so let's close it here and move the discussion to discourse.

**Comment by brucellino** [comment]
This issue was moved to http://discourse.sci-gaia.eu/t/puppet-cvmfs-submodule/2354
