### ISSUE TITLE
become is not a legal parameter

### ISSUE THREAD

**Issue by mekuanent** [AAROC/DevOps#357]
ERROR: become is not a legal parameter in an Ansible task or handler

**Comment by brucellino** [comment]
hi @mekuanent - could you please provide  the full output of the playbook ? I can't tell which task is failing.

**Comment by eyu-se** [comment]
hi @brucellino  that is the only out put 
the variable become is mentioned in both idp-ldap.yml and shibv3idp-ldap.yml

**Comment by brucellino** [comment]
Yes, become is the [privilege escalation](http://docs.ansible.com/ansible/become.html) means in Ansible (_ie_ it's how you tell Ansible to escalate privilege) - so, not a variable, but a parameter of a task. 

I can't reproduce this error in the `master` branch - syntax check shows no problems. 
```
ansible-playbook -i inventories/inventory.ethernet.edu.et shibv3idp-ldap.yml --syntax-check

playbook: shibv3idp-ldap.yml
```


Can you tell me which version of Ansible you're using ? 
```
ansible --version
ansible 2.3.0
```
Also, check that you are up to date, by pulling the master branch : 

```
git pull origin master
From https://github.com/AAROC/DevOps
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```

**Comment by eyu-se** [comment]
version is ansible 1.7.2

**Comment by brucellino** [comment]
Ah - that's not going to work :cry: You need 2.x. Could you get the latest release from pip, as described [in the docs](http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-pip) ?
