### ISSUE TITLE
Permission denied error on remote machine.

### ISSUE THREAD

**Issue by okoliec** [AAROC/DevOps#360]
I was trying to install my idp-ldap. I have created an ansible user on the remote machine with sudo access. I have also copied keys from the control system to the remote machine. 
Please how will i fix the error.

TASK [bootstrap : Do raw replace of nameserver] ********************************
task path: /home/ansible/DevOps/Ansible/roles/bootstrap/tasks/prerequisites.yml:22
fatal: [ldap.unilag.edu.ng]: FAILED! => {"changed": true, "failed": true, "rc": 4, "stderr": "Shared connection to ldap.unilag.edu.ng closed.\r\n", "stdout": "sed: couldn't open temporary file /etc/sedFg38cI: Permission denied\r\n", "stdout_lines": ["sed: couldn't open temporary file /etc/sedFg38cI: Permission denied"]}
fatal: [idp.unilag.edu.ng]: FAILED! => {"changed": true, "failed": true, "rc": 4, "stderr": "Shared connection to idp.unilag.edu.ng closed.\r\n", "stdout": "sed: couldn't open temporary file /etc/sedBlOrpM: Permission denied\r\n", "stdout_lines": ["sed: couldn't open temporary file /etc/sedBlOrpM: Permission denied"]}
	to retry, use: --limit @/home/ansible/DevOps/Ansible/bootstrap.retry

**Comment by brucellino** [comment]
Hi @okoliec  This is a network error : 
` "Shared connection to ldap.unilag.edu.ng closed"`

The bootstrap role uses the remote root user to bring the machine to a known state. If you want to ensure that user keys are present, then add them to the `files/public_keys` in the bootstrap role. These are used by the role to assemble the authorized_keys.

See https://github.com/AAROC/DevOps/blob/master/Ansible/roles/bootstrap/tasks/keys.yml

**Comment by okoliec** [comment]
Hello @brucellino 

I added the keys to the files/public_keys. I was wondering if i was doing something wrong. I will check it again.
Thanks for your prompt response
