### ISSUE TITLE
Clarification on ansible user

### ISSUE THREAD

**Issue by okoliec** [AAROC/DevOps#361]
Please I need some clarification on the ansible install from the remote to the control.

My understanding of the installation process is that i will have a user ansible on both machines and then add the ansible user on the remote machine to the sudoers file and then copied ssh-key from the control machine to the remote so that the user is not prompted for password.

The issue is that each time i tried running the bootstrap.yml it complains about user not having permission to install on the remote machine.

Please can you guide me on how to set the initial system up for the installation. I want to deploy an ldap and idp on a remote machine.

**Comment by brucellino** [comment]
Hi @okoliec - could you please ask this on [the forum](https://discourse.sci-gaia.eu). If you have trouble logging in, we can carry on here.
