### ISSUE TITLE
Liferay on Glassfish3 blank screen

### ISSUE THREAD

**Issue by damas** [AAROC/DevOps#74]
Hi Bruce,
Just reinstalled Liferay with Glassfish 3 as per document http://sourceforge.net/p/ctsciencegtwys/wiki/InstallLiferay611/ but I am getting a blank screen at http://sgw.ternet.or.tz:8080/
Can you please assist to fix with this problem?
Rgds,
Damas

**Comment by brucellino** [comment]
Fixed in 8db2b0b
